#!/usr/bin/env bash
#
# One-command launcher for the full S500 ArUco-landing SITL stack.
#
#   Terminal layout (5 components):
#     1. sim         - PX4 + Gazebo (run_simulation)   [interactive pxh> shell]
#     2. mavros      - PX4 <-> ROS 2 bridge
#     3. cam_bridge  - Gazebo camera -> /camera/image_raw + /camera/camera_info
#     4. detector    - aruco_detector_node
#     5. controller  - landing_controller_node (auto_offboard)
#
# Uses tmux if available (one window, 5 panes). Otherwise falls back to
# separate gnome-terminal windows. Waits for the sim to publish its camera
# topic before starting the ROS side, so MAVROS never sees a time jump.
#
# Usage:
#   ./tools/run_sim_stack.sh            # start everything
#   tmux attach -t s500sim              # re-attach (tmux mode)
#   tmux kill-session -t s500sim        # stop everything (tmux mode)

set -euo pipefail

SIM_DIR="$HOME/Projects/Quads_Project/drone_dev_sim"
WS_DIR="$HOME/Projects/Quads_Project/drone_dev"
PARAMS="$WS_DIR/src/landing_controller_node/config/landing_params.yaml"
ROS_SETUP="/opt/ros/humble/setup.bash"
SESSION="s500sim"

# The sim pane writes its exit status here if run_simulation ever returns.
SIM_STATUS_FILE="/tmp/run_sim_stack.$USER.simstatus"
USE_TMUX=0

# Anaconda shadows the system protobuf/protoc/python and breaks the PX4 gz
# build ("generated by an older version of protoc"). 'conda deactivate' is NOT
# enough: ~/.bashrc's conda-init fallback hardcodes anaconda3/bin onto PATH
# regardless of activation. So compute a PATH with every anaconda entry
# stripped, and force it at the start of every pane (runs after the pane's
# profile files, so it wins).
CLEAN_PATH="$(echo "$PATH" | tr ':' '\n' | grep -v anaconda3 | paste -sd: -)"
DEACT="export PATH='$CLEAN_PATH'; unset PYTHONHOME CONDA_PREFIX CONDA_DEFAULT_ENV 2>/dev/null;"

# Commands for each component (each self-contained: sources what it needs).
CMD_SIM="$DEACT cd '$SIM_DIR' && cmake --build build --target run_simulation"
CMD_MAVROS="$DEACT source '$ROS_SETUP' && ros2 launch mavros px4.launch fcu_url:=\"udp://:14540@127.0.0.1:14580\""
CMD_BRIDGE="$DEACT source '$ROS_SETUP' && ros2 run ros_gz_bridge parameter_bridge \
  /down_camera@sensor_msgs/msg/Image@gz.msgs.Image \
  /camera_info@sensor_msgs/msg/CameraInfo@gz.msgs.CameraInfo \
  --ros-args -r /down_camera:=/camera/image_raw -r /camera_info:=/camera/camera_info"
CMD_DETECTOR="$DEACT source '$ROS_SETUP' && source '$WS_DIR/install/setup.bash' && ros2 run aruco_detector_node aruco_detector_node"
# The controller sends its OFFBOARD+arm request ONCE at startup; if PX4 is
# still initializing (EKF not converged), arming is rejected and never retried.
# So wait for the MAVROS<->PX4 link, then give the EKF time to settle.
CMD_CONTROLLER="$DEACT source '$ROS_SETUP' && source '$WS_DIR/install/setup.bash' && \
echo '[stack] waiting for MAVROS<->PX4 link...' && \
until ros2 topic echo /mavros/state --once 2>/dev/null | grep -q 'connected: true'; do sleep 2; done && \
echo '[stack] link up; letting EKF settle (20 s)...' && sleep 20 && \
ros2 run landing_controller landing_controller_node --ros-args --params-file '$PARAMS' -p auto_offboard:=true"

# Kill orphaned sim processes from previous runs. Without this, PX4 finds a
# stale gz server already publishing a clock, assumes Gazebo is running, and
# never launches a new GUI window.
cleanup_orphans() {
    echo "[run_sim_stack] cleaning up any orphaned gz/px4 processes..."
    pkill -f 'gz sim'                        2>/dev/null || true
    pkill -f 'px4_sitl_default/bin/px4'      2>/dev/null || true
    sleep 1
}

# 'cmake --build' needs an already-configured cache; build/CMakeCache.txt is
# generated and gitignored, so a fresh clone (or a wiped build/) has none and
# the sim pane dies instantly with "Error: could not load cache". Configure
# here rather than in the pane so a failure aborts the script visibly. Must run
# under the anaconda-stripped PATH, or cmake bakes conda's toolchain into the
# cache.
ensure_configured() {
    [[ -f "$SIM_DIR/build/CMakeCache.txt" ]] && return 0
    echo "[run_sim_stack] build/ is not configured; running cmake configure..."
    bash -lc "$DEACT cmake -S '$SIM_DIR' -B '$SIM_DIR/build'"
}

# Block until Gazebo is publishing the down-camera topic (sim is up), or bail.
wait_for_sim() {
    rm -f "$SIM_STATUS_FILE"
    echo "[run_sim_stack] waiting for Gazebo camera topic (sim boot)..."
    for _ in $(seq 1 180); do
        if gz topic -l 2>/dev/null | grep -q "/down_camera"; then
            echo "[run_sim_stack] sim is up."
            return 0
        fi
        # Every pane runs 'exec bash' after its command, so a crashed sim keeps
        # its pane alive at a prompt and looks identical to a slow-booting one.
        # The status file is the only signal that it stopped.
        if [[ -f "$SIM_STATUS_FILE" ]]; then
            echo "[run_sim_stack] ERROR: sim exited (status $(cat "$SIM_STATUS_FILE"))" \
                 "without publishing /down_camera." >&2
            if [[ "$USE_TMUX" == 1 ]]; then
                echo "[run_sim_stack] last output from the sim pane:" >&2
                tmux capture-pane -p -t "$SESSION:0.0" 2>/dev/null \
                    | grep -v '^[[:space:]]*$' | tail -20 >&2
                echo "[run_sim_stack] sim pane left open for inspection:" \
                     "tmux attach -t $SESSION" >&2
            fi
            exit 1
        fi
        sleep 2
    done
    echo "[run_sim_stack] WARNING: sim not detected after 6 min; starting ROS side anyway." >&2
}

if command -v tmux >/dev/null 2>&1; then
    tmux has-session -t "$SESSION" 2>/dev/null && {
        echo "Session '$SESSION' already running. Attach: tmux attach -t $SESSION"; exit 0; }

    USE_TMUX=1
    ensure_configured
    cleanup_orphans

    # Pane 0: sim. \\\$? survives both bash's expansion here and sh's inside
    # tmux, so the status recorded is run_simulation's, not a shell's.
    tmux new-session -d -s "$SESSION" -n stack \
        "bash -lc \"$CMD_SIM; echo \\\$? > '$SIM_STATUS_FILE'; exec bash\""

    wait_for_sim

    # Split into 5 panes and launch the rest.
    tmux split-window -v -t "$SESSION:0" "bash -lc \"$CMD_MAVROS; exec bash\""
    tmux split-window -h -t "$SESSION:0" "bash -lc \"$CMD_BRIDGE; exec bash\""
    sleep 3
    tmux select-pane -t "$SESSION:0.0"
    tmux split-window -h -t "$SESSION:0" "bash -lc \"$CMD_DETECTOR; exec bash\""
    tmux split-window -v -t "$SESSION:0" "bash -lc \"sleep 3; $CMD_CONTROLLER; exec bash\""
    tmux select-layout -t "$SESSION:0" tiled

    echo "Started tmux session '$SESSION'. Attaching (detach: Ctrl-b d; stop: tmux kill-session -t $SESSION)"
    tmux attach -t "$SESSION"

elif command -v gnome-terminal >/dev/null 2>&1; then
    echo "[run_sim_stack] tmux not found; opening gnome-terminal windows."
    ensure_configured
    gnome-terminal --title="1-sim" -- \
        bash -lc "$CMD_SIM; echo \$? > '$SIM_STATUS_FILE'; exec bash"
    wait_for_sim
    gnome-terminal --title="2-mavros"     -- bash -lc "$CMD_MAVROS; exec bash"
    gnome-terminal --title="3-cam_bridge" -- bash -lc "$CMD_BRIDGE; exec bash"
    sleep 3
    gnome-terminal --title="4-detector"   -- bash -lc "$CMD_DETECTOR; exec bash"
    gnome-terminal --title="5-controller" -- bash -lc "sleep 3; $CMD_CONTROLLER; exec bash"
    echo "[run_sim_stack] all windows launched. Close them individually to stop."

else
    echo "ERROR: need either tmux or gnome-terminal. Install tmux: sudo apt install tmux" >&2
    exit 1
fi
